name: Release

on:
  push:
    branches:
      - main # Or your default branch, e.g., master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues/PRs
      pull-requests: write # to be able to comment on released PRs
      id-token: write # to enable use of OIDC for npm provenance

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necessary for semantic-release to determine changes

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*" # Use the latest LTS version of Node.js

      - name: Install dependencies
        run: npm ci # Assuming this is an npm project, otherwise use yarn install or similar

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release 